parameters:

services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  App\DataFixtures\:
    resource: '../src/DataFixtures/'
    public: true

  ######################################### Services #########################################

  App\Util\PasswordOperator\TestPasswordOperator:
  App\Util\PasswordOperator\PasswordOperator:
    alias: App\Util\PasswordOperator\TestPasswordOperator

  App\Util\DateProvider\TestDateProvider:
  App\Util\DateProvider\DateProvider:
    alias: App\Util\DateProvider\TestDateProvider

  App\Util\EventDispatcher\Infrastructure\Sync\SymfonyEventDispatcherAdapter:
    arguments:
      - '@event_dispatcher'
  App\Util\EventDispatcher\EventDispatcher:
    alias: App\Util\EventDispatcher\Infrastructure\Sync\SymfonyEventDispatcherAdapter

  ######################################### Services #########################################
