# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    ######################################### Context #########################################
    App\:
        resource: '../src/'
        exclude:
            - 'Kernel.php'
            - '../src/Tests/'

    App\SharedKernel\:
        resource: '../src/SharedKernel/'
        exclude:
            - 'Application/'
            - 'Domain/'
            - 'Infrastructure/'
            - 'Test/'

    App\FilesDataBase\:
        resource: '../src/FilesDataBase/'
        exclude:
            - 'DataBase/'

    App\ScheduleCalculation\:
        resource: '../src/ScheduleCalculation/'
        exclude:
            - 'Entity/'
            - 'Repository/'
            - 'Service/'
            - 'UseCase/'

    App\UserAccess\:
        resource: '../src/UserAccess/'
        exclude:
            - 'Entity/'
            - 'Repository/'
            - 'Service/'
            - 'UseCase/'

    App\Profiles\:
        resource: '../src/Profiles/'
        exclude:
            - 'Application/'
            - 'Domain/'
            - 'Infrastructure/'
            - 'Test/'
    ######################################### Context #########################################

    ######################################### Services #########################################
    App\SharedKernel\Infrastructure\Typiser\Typiser:
    App\SharedKernel\Application\Service\Typiser:
        alias: App\SharedKernel\Infrastructure\Typiser\Typiser

    App\SharedKernel\Infrastructure\Validator\Validator:
    App\SharedKernel\Application\Service\Validator:
        alias: App\SharedKernel\Infrastructure\Validator\Validator

    App\Util\PasswordOperator\HashPasswordOperator:
    App\Util\PasswordOperator\PasswordOperator:
        alias: App\Util\PasswordOperator\HashPasswordOperator

    App\Util\EventDispatcher\Infrastructure\Sync\SymfonyEventDispatcherAdapter:
        arguments:
            - '@event_dispatcher'
    App\Util\EventDispatcher\EventDispatcher:
        alias: App\Util\EventDispatcher\Infrastructure\Sync\SymfonyEventDispatcherAdapter

    App\SharedKernel\Domain\Settings\Settings:

    App\UserAccess\Infrastructure\Security\OAuthUserProvider:
    Symfony\Component\Security\Core\User:
        alias: App\UserAccess\Infrastructure\Security\OAuthUserProvider

    App\UserAccess\Infrastructure\Security\AuthService:
        alias: App\UserAccess\Infrastructure\Security\SymfonyTokenStorageAuthService

    App\UserAccess\Infrastructure\Security\SymfonyTokenStorageAuthService:
        arguments:
            - '@security.token_storage'

    ######################################### Services #########################################

    ######################################### Repositories #########################################
#    App\UserAccess\Infrastructure\Repository\FileSystemUserRepository:
#        arguments:
#            - '@App\FilesDataBase\OperatorSCV'
#            - '%env(resolve:USER_DATA_SOURCE)%'

    App\UserAccess\Infrastructure\Repository\DoctrineUserRepository:
    App\UserAccess\Domain\UserRepository:
        alias: App\UserAccess\Infrastructure\Repository\DoctrineUserRepository

    App\Profiles\Infrastructure\Repository\FanRepository:
        public: true

    App\Profiles\Infrastructure\Repository\MusicianRepository:
        public: true

    App\Profiles\Infrastructure\Repository\ProducerRepository:
        public: true

    ######################################### Repositories #########################################

    ######################################### Listeners #########################################
    App\SharedKernel\Infrastructure\EventListeners\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    App\SharedKernel\Infrastructure\EventListeners\UserAccess\CreatedListener:
        tags:
            - { name: kernel.event_listener, event: App\UserAccess\Domain\UserCreated, method: onEventMessages }

    App\UserAccess\Application\Listeners\UserResolveListener:
        arguments:
            - '@Symfony\Component\Security\Core\User'
            - '@App\Util\PasswordOperator\PasswordOperator'
        tags:
            - { name: kernel.event_listener, event: trikoder.oauth2.user_resolve, method: onUserResolve }

    App\SharedKernel\Infrastructure\EventListeners\JsonDecoderListener:
        arguments:
            - '@logger'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    App\SharedKernel\Infrastructure\EventListeners\CORSListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    App\SharedKernel\Infrastructure\EventListeners\PreflightRequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 33 }
    ######################################### Listeners #########################################

    ######################################### Controllers #########################################
    App\Api\Controller\Http\:
        resource: '../src/Api/Controller/Http'
        tags: [ 'controller.service_arguments' ]
    ######################################### Controllers #########################################
