parameters:

services:

  _defaults:
    autowire: true
    autoconfigure: true

  App\DataFixtures\:
    resource: '../src/DataFixtures/'
    public: true

  ######################################### Services #########################################

  App\Util\PasswordOperator\TestPasswordOperator:
  App\Util\PasswordOperator\PasswordOperator:
    alias: App\Util\PasswordOperator\TestPasswordOperator

  ######################################### Services #########################################
