version: '3.7'

services:

  gateway:
    build:
      context: gateway/docker/development/nginx
    restart: always
    ports:
    - "8080:8080"
    - "8081:8081"
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: backend/docker/development/nginx
    volumes:
      - ./backend:/app
    restart: always
    depends_on:
      - php-fpm

  frontend:
    build:
      context: frontend/docker/development/nginx
    volumes:
    - ./frontend:/app
    restart: always
    depends_on:
      - frontend-node

  frontend-node:
    build:
      context: frontend/docker/development/node
    volumes:
      - './frontend:/app'
    environment:
      BACKEND_API_URL: http://localhost/web
    command: bash -c "npm install && npm run start"

  php-fpm:
    build:
      context: backend/docker/development/php-fpm
    environment:
      DATABASE_URL: mysql://dbuser:dbuserpass@db:3306/progressing
      APP_SECRET: 8d6efe5f71a7c9a3c6c2854d44fed71d
      TEST_DATABASE_URL: mysql://root:root@db:3306/progressing_test
      OAUTH_ENCRYPTION_KEY: N5GMdLSHHdFo6dOny1OhLNxDgwi63ZhdXLEvDvu9PPo=
      OAUTH_PUBLIC_KEY: /run/secrets/jwt_public_key
      OAUTH_PRIVATE_KEY: /run/secrets/jwt_private_key
      APP_ENV: dev
    secrets:
      - jwt_public_key
      - jwt_private_key
    restart: always
    depends_on:
      - db
    volumes:
      - ./backend:/app

  php-cli:
    build:
      context: backend/docker/development/php-cli
    environment:
      DATABASE_URL: mysql://dbuser:dbuserpass@db:3306/progressing
      APP_SECRET: 8d6efe5f71a7c9a3c6c2854d44fed71d
      TEST_DATABASE_URL: mysql://root:root@db:3306/progressing_test
      OAUTH_ENCRYPTION_KEY: N5GMdLSHHdFo6dOny1OhLNxDgwi63ZhdXLEvDvu9PPo=
      OAUTH_PUBLIC_KEY: /run/secrets/jwt_public_key
      OAUTH_PRIVATE_KEY: /run/secrets/jwt_private_key
      APP_ENV: dev
    secrets:
      - jwt_public_key
      - jwt_private_key
    depends_on:
      - db
    volumes:
    - ./backend:/app

  db:
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: progressing
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpass
    ports:
      - 3310:3306

volumes:
  db:

secrets:
  jwt_public_key:
    file: ./backend/docker/development/secrets/jwt_public.key
  jwt_private_key:
    file: ./backend/docker/development/secrets/jwt_private.key
