version: '3.7'

services:

  gateway:
    image: ${REGISTRY_ADDRESS}/progressing-app-gateway:${IMAGE_TAG}
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html:ro
    depends_on:
      - backend
      - frontend

  backend:
    image: ${REGISTRY_ADDRESS}/progressing-app-backend:${IMAGE_TAG}
    restart: always
    depends_on:
      - php-fpm
      - php-cli

  frontend-node:
    image: ${REGISTRY_ADDRESS}/progressing-app-frontend:${IMAGE_TAG}
    restart: always
    environment:
      APP_ENV: prod
      BACKEND_API_URL: ${BACKEND_API_URL}

  php-fpm:
    image: ${REGISTRY_ADDRESS}/progressing-app-backend-php-fpm:${IMAGE_TAG}
    restart: always
    environment:
      APP_ENV: prod
      DATABASE_URL: pgsql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}?serverVersion=13&charset=utf8
      APP_SECRET: 8d6efe5f71a7c9a3c6c2854d44fed71d
      TEST_DATABASE_URL: pgsql://${DB_ROOT_PASSWORD}:${DB_ROOT_PASSWORD}@${DB_HOST}:5432/${DB_TEST_NAME}?serverVersion=13&charset=utf8
      JWT_ENCRYPTION_KEY: ${JWT_ENCRYPTION_KEY}
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
    secrets:
      - jwt_public_key
      - jwt_private_key

  php-cli:
    image: ${REGISTRY_ADDRESS}/progressing-app-backend-php-cli:${IMAGE_TAG}
    restart: always
    environment:
      APP_ENV: prod
      DATABASE_URL: pgsql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}?serverVersion=13&charset=utf8
      APP_SECRET: 8d6efe5f71a7c9a3c6c2854d44fed71d
      TEST_DATABASE_URL: pgsql://${DB_ROOT_PASSWORD}:${DB_ROOT_PASSWORD}@${DB_HOST}:5432/${DB_TEST_NAME}?serverVersion=13&charset=utf8
      JWT_ENCRYPTION_KEY: ${JWT_ENCRYPTION_KEY}
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
    secrets:
      - jwt_public_key
      - jwt_private_key

secrets:
  jwt_public_key:
    file: ./backend/docker/production/secrets/jwt_public.key
  jwt_private_key:
    file: ./backend/docker/production/secrets/jwt_private.key
