security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        oauth_provider:
            id: App\UserAccess\Infrastructure\Security\OAuthUserProvider

    encoders:
        App\UserAccess\Infrastructure\Security\UserIdentity:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        open_api:
            pattern: "^/(api/token$|sign-up)"
            security: false
        main:
            anonymous: true
            security: true
            stateless: true
            oauth2: true
            provider: oauth_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/authorize, roles: PUBLIC_ACCESS }
